version: "2"

services:
  vote:
    environment:
      - REDIS_HOST
    build: ./vote
    command: python app.py
    volumes:
      - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  inventory-service:
      image: docker.io/etbe/inventory
      volumes:
        - ./inventory/contract-interface.yaml:/app/contract-interface.yaml
      ports:
        - "1350:1350"

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
